# Generated by Django 5.0 on 2024-03-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_branch_bank_branch_banks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='banks',
        ),
        migrations.AddField(
            model_name='branch',
            name='bank',
            field=models.ManyToManyField(related_name='bank', to='api.bank'),
        ),
    ]
