# Generated by Django 5.0 on 2024-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_branch_banks_branch_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bank',
            field=models.ManyToManyField(related_name='branches', to='api.bank'),
        ),
    ]
